{% set version = "1.8.0" %}

package:
  name: tensorflow-base
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 47646952590fd213b747247e6870d89bb4a368a95ae3561513d6c76e44f92a75
  patches:
    - 0001-add-rt-to-linkopts.patch                   # [linux]

build:
  string: with_mkldnn
  skip: True  # [not linux64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # conda build requirements
    - bazel >=0.5.4
    - pip
    - python
    - swig
    - zlib
    # requirements specified by the package itself
    - wheel >=0.26
    - termcolor >=1.1.0
    - six >=1.10.0
    - protobuf >=3.4.0
    - numpy 1.13.3
    - mock >=2.0.0        # [py2k]
    - grpcio >=1.8.6
    - gast >=0.2.0
    - enum34 >=1.1.6      # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - astor >=0.6.0
    - absl-py >=0.1.6
    # the following packages are required for testing
    - portpicker
    - scipy
    - scikit-learn
  run:
    - python
    - termcolor >=1.1.0
    - six >=1.10.0
    - protobuf >=3.4.0
    - {{ pin_compatible('numpy') }}
    - mock >=2.0.0        # [py2k]
    - grpcio >=1.8.6
    - gast >=0.2.0
    - enum34 >=1.1.6      # [py2k]
    - backports.weakref >=1.0rc1  # [py2k]
    - astor >=0.6.0
    - absl-py >=0.1.6

test:
  imports:
    - tensorflow
  commands:
    - conda inspect linkages -p $PREFIX tensorflow-base  # [linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
